apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: namespace-g3
  labels:
    app: g3-auth
spec:
  type: ClusterIP
  selector:
    app: g3-auth
  ports:
    - port: 8081
      targetPort: 8081
